version: 2
updates:
  # Enable version updates for npm (pnpm uses package.json)
  - package-ecosystem: 'npm'
    directory: '/apps/web'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    reviewers:
      - 'the.ultimate.closers'
    labels:
      - 'dependencies'
      - 'security'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: '/apps/api'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    reviewers:
      - 'the.ultimate.closers'
    labels:
      - 'dependencies'
      - 'security'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'npm'
    directory: '/packages/eslint-config'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    reviewers:
      - 'the.ultimate.closers'
    labels:
      - 'dependencies'
      - 'security'
    commit-message:
      prefix: 'chore(deps)'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'ci'
    commit-message:
      prefix: 'chore(ci)'
