name: OSV Scanner

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  osv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -sSfL https://raw.githubusercontent.com/google/osv-scanner/main/install.sh | sh -s -- -b /usr/local/bin
          /usr/local/bin/osv-scanner -r . --lockfile --format sarif > osv.sarif || true
      - uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: osv.sarif

